# Configuration file for the models
# See README.md for more details

############ Diffusion ############

diff_sd1-5:
  image_size: [768, 768]
  batch_size: 32
  model: 'runwayml/stable-diffusion-v1-5'
  layers: [5] #[0, 3, 5, 8, 11, 13, 15]
  step: 201

diff_sd2-1:
  image_size: [768, 768]
  batch_size: 32
  model: 'stabilityai/stable-diffusion-2-1'
  layers: [0, 3, 5, 8, 11, 13, 15]
  step: 261

diff_hook_sd2-1:
  image_size: [768, 768]
  batch_size: 32
  model: 'stabilityai/stable-diffusion-2-1'
  layers: []
  step: 261

diff_sdxl:
  image_size: [768, 768] # [1024, 1024], [768, 768]
  batch_size: 32 # 16, 32
  model: "stabilityai/stable-diffusion-xl-base-1.0"
  layers: [1] #[0, 1, 2, 4, 5, 7, 9, 11]
  step: 101 # 201, 101

diff_lcm:
  image_size: [1024, 1024] #[768, 768]
  batch_size: 16 #32
  model: "latent-consistency/lcm-sdxl"
  layers: [1] #[0, 1, 2, 4, 5, 7, 9, 11]
  step: 64

diff_add:
  image_size: [768, 768] # -> [1280, 24, 24]
  batch_size: 32
  model: "stabilityai/sdxl-turbo"
  layers: [1]
  step: 101

dit:
  image_size: [768, 768]
  batch_size: 32
  layers: [10]
  step: 0
  image_range: [0, 1]

############ DINO ############

dinov1_s8:
  image_size: [224, 224]
  batch_size: 32
  version: 1
  model_size: 's'
  patch_size: 8
  registers: false
  image_range: [0, 1]
  layers: [2, 4, 6, 9, 10, 11]

dinov2_b14:
  image_size: [840, 840]
  batch_size: 64
  version: 2
  model_size: 'b'
  patch_size: 14
  registers: false
  image_range: [0, 1]
  layers: [11] #[2, 4, 6, 9, 10, 11]

dinov2_b14_reg:
  image_size: [840, 840]
  batch_size: 64
  version: 2
  model_size: 'b'
  patch_size: 14
  registers: true
  image_range: [0, 1]
  layers: [11] # [2, 4, 6, 9, 10, 11]

dinov2_large:
  image_size: [840, 840]
  batch_size: 64
  version: 2
  model_size: 'l'
  patch_size: 14
  registers: false
  image_range: [0, 1]
  layers: [23]

dinov2_b14_reg_s:
  image_size: [434, 434]
  batch_size: 64
  version: 2
  model_size: 'b'
  patch_size: 14
  registers: true
  image_range: [0, 1]
  layers: [11]

############ OpenCLIP ############

clip:
  image_size: [336, 336]
  batch_size: 64
  image_range: [0, 1]
  layers: [11] #[2, 4, 6, 9, 10, 11]

############ MAE ############

# download weights using the following command:
# wget https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_large.pth

mae:
  image_size: [224, 224]
  batch_size: 32
  model_path : '.cache/mae_visualize_vit_large.pth'
  arch: 'mae_vit_large_patch16' # mae_vit_large_patch16, mae_vit_huge_patch14
  patch_size: 16 # 14, 16
  image_range: [0, 1]
  layers: [3, 8, 13, 18, 23, 24, 26, 29, 31]

############ Depth ############

zoedepth:
  image_size: [512, 384]
  batch_size: 32
  version: 'NK' # N, K, NK
  image_range: [0, 1]
  layers: [0, 8, 10, 16, 23, 25, 27, 29]

############ GAN ############

gan_lafite:
  image_size: [256, 256]
  batch_size: 1
  model_path : 'lafite'
  layers: null
  image_range: [0, 1]
  grad_enabled: true

############ I-JEPA ############

ijepa:
  image_size: [448, 448]
  batch_size: 32
  image_range: [0, 1]
  layers: [31] #[21, 24, 27, 31] [31]

########### EfficientViT ############

efficientvit:
  image_size: [224, 224]
  batch_size: 64
  image_range: [0, 1]
  layers: [6, 12, 18, 26] # 27 blocks in 4 stages (4, 6, 7, 10)


############ Combination ############

combination_add:
  image_size: [980, 980]
  batch_size: 16
  image_range: [0, 1]
  model1: 'diff_add'
  model2: 'dinov2_b14_reg'
  model1_config:
    model: "stabilityai/sdxl-turbo"
    layers: [1] #[1, 4, 7]
    step: 101
  model2_config:
    version: 2
    model_size: 'b'
    patch_size: 14
    registers: true
    layers: [11]

combination_1-5:
  image_size: [840, 840]
  batch_size: 16
  image_range: [0, 1]
  model1: 'diff_sd1-5'
  model2: 'dinov2_b14'
  model1_config:
    model: 'runwayml/stable-diffusion-v1-5'
    layers: [3, 7, 11]
    step: 201
  model2_config:
    version: 2
    model_size: 'b'
    patch_size: 14
    registers: false
    layers: [11]

combination_ijepa:
  image_size: [448, 448]
  batch_size: 16
  image_range: [0, 1]
  model1: 'diff_add'
  model2: 'ijepa'
  model1_config:
    model: "stabilityai/sdxl-turbo"
    layers: [1] #[1, 4, 7]
    step: 101
  model2_config:
    layers: [31]

combination_add_clip:
  batch_size: 16
  image_range: [0, 1]
  model1: 'diff_add'
  model2: 'dinov2_b14_reg'
  model3: 'clip'
  model1_config:
    model: "stabilityai/sdxl-turbo"
    image_size: [980, 980]
    layers: [1] #[1, 4, 7]
    step: 101
  model2_config:
    image_size: [840, 840]
    version: 2
    model_size: 'b'
    patch_size: 14
    registers: true
    layers: [11]
  model3_config:
    image_size: [336, 336]
    layers: [11]


############ Ensemble ############

ensemble_ts:
  image_size: [768, 768]
  batch_size: 8
  model: "stabilityai/sdxl-turbo"
  layers: [1]
  steps: [101]
  ensemble_size: 4
  random_cropping: false

############ Prompt ############

prompt:
  image_size: [768, 768]
  batch_size: 32
  model: "stabilityai/sdxl-turbo"
  layers: [1]
  step: 101
  prompt_mode: 'caption'

############ Distilled Models ############

distilled_model:
  image_size: [434, 434]
  batch_size: 1
  image_range: [0, 1]
  weights: "checkpoints/distilled_us_best_co3d/pytorch_model.bin"
  rank: 8
  lora_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  lora_dropout: 0
  learned_upsampler: false
  window_softargmax: false
  pose_align: false # only in non-cache mode
